[build-system]
requires = ["hatchling>=1.10.0", "jupyter-client"]
build-backend = "hatchling.build"

[project]
dependencies = [
    "pydantic>=2.12.3",
    "pydantic-ai>=1.101.0",
    "pyyaml>=6.0.3",
    "metakernel>=1.0.0",
    "statikomand>=0.1.1",
]
name = "pydantic-ai-kernel"
dynamic = ["version"]
description = "Base kernel for pydantic-ai kernels"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE-2.0.txt" }
authors = [
    { name = "Marius Garénaux Gruau", email = "marius.garenaux-gruau@irisa.fr" },
]
maintainers = [
    { name = "Marius Garénaux Gruau", email = "marius.garenaux-gruau@irisa.fr" },
]
keywords = ["ai", "kernel", "jupyter", "pydantic-ai", "agent"]

[project.urls]
Repository = "https://github.com/mariusgarenaux/pydantic-ai-kernel"


[tool.hatch.version]
path = "pydantic_ai_kernel/__init__.py"


[tool.hatch.metadata]
allow-direct-references = true
# Used to call hatch_build.py
[tool.hatch.build.hooks.custom]

[tool.hatch.build.targets.sdist]
include = ["/pydantic_ai_kernel"]

[tool.hatch.build.targets.wheel.shared-data]
"data_kernelspec/share" = "share"

[dependency-groups]
dev = [
    "build>=1.4.0",
    "hatchling>=1.10.0",
    "jupyter-client>=8.7.0",
    "jupyter-console>=6.6.3",
    "jupyter-kernel-test>=0.7.0",
    "mkdocs>=1.6.1",
    "pytest>=9.0.2",
    "twine>=6.2.0",
]
